CREATE DATABASE IF NOT EXISTS movie_db;
CREATE DATABASE IF NOT EXISTS seat_db;
CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS booking_db;
CREATE DATABASE IF NOT EXISTS notification_db;
